# Generated by Django 3.2.3 on 2021-07-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='now_attending',
            field=models.CharField(choices=[('AWS', 'AWS'), ('DevOps', 'DevOps'), ('Azure', 'Azure'), ('React', 'React'), ('Java', 'Java'), ('Python', 'Python'), ('WebDevelopment', 'WebDevelopment')], max_length=100),
        ),
    ]
