# Generated by Django 3.2.3 on 2021-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_student_now_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_enrolled',
            field=models.ManyToManyField(related_name='course_enrolled', to='data.Course'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='now_attending',
        ),
        migrations.AddField(
            model_name='student',
            name='now_attending',
            field=models.ManyToManyField(related_name='now_attending', to='data.Course'),
        ),
    ]
