# Generated by Django 3.2.3 on 2021-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210701_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half')], default='half', max_length=10),
        ),
    ]
