# Generated by Django 3.2.3 on 2021-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_batch_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], default='Weekday', max_length=100, null=True),
        ),
    ]
