# Generated by Django 3.2.3 on 2021-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_trainertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainertask',
            options={'ordering': ['complete', '-created']},
        ),
        migrations.AddField(
            model_name='trainertask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
