# Generated by Django 3.2.3 on 2021-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210704_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shared',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
