# Generated by Django 3.2.3 on 2021-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_student_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='street2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
