# Generated by Django 3.2.3 on 2021-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_studentcoursedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursedata',
            name='status',
            field=models.CharField(choices=[('Yet to start', 'Yet to start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
