# Generated by Django 3.2.3 on 2021-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_studentcoursedata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='studentcoursedata',
            name='status',
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Yet to start', 'Yet to start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
