# Generated by Django 3.2.3 on 2021-07-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20210708_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursedata',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.student'),
        ),
    ]
